/* CSS - Cascading Style Sheet */
/* Palette color codes */
/* Palette URL: http://paletton.com/#uid=72N1e0kn3pHhvJNmXygDCnICQw1 */

/* Feel free to copy&paste color codes to your application */


/* As hex codes */

.color-primary-0 { color: #3AA82F }	/* Main Primary color */
// green
.color-primary-1 { color: #74E668 }
.color-primary-2 { color: #4AD43C }
.color-primary-3 { color: #0F9B00 }
.color-primary-4 { color: #14D100 }
// blue
.color-secondary-1-0 { color: #39378F }	/* Main Secondary color (1) */
.color-secondary-1-1 { color: #7472D6 }
.color-secondary-1-2 { color: #4947B8 }
.color-secondary-1-3 { color: #100E84 }
.color-secondary-1-4 { color: #1714B2 }
// yellow
.color-secondary-2-0 { color: #CDA939 }	/* Main Secondary color (2) */
.color-secondary-2-1 { color: #FFDD74 }
.color-secondary-2-2 { color: #FFD248 }
.color-secondary-2-3 { color: #BD8F00 }
.color-secondary-2-4 { color: #FFC000 }
// red
.color-complement-0 { color: #C9383F }	/* Main Complement color */
.color-complement-1 { color: #FD7379 }
.color-complement-2 { color: #FB4750 }
.color-complement-3 { color: #BA0009 }
.color-complement-4 { color: #FB000D }



/* As RGBa codes */

.rgba-primary-0 { color: rgba( 58,168, 47,1) }	/* Main Primary color */
.rgba-primary-1 { color: rgba(116,230,104,1) }
.rgba-primary-2 { color: rgba( 74,212, 60,1) }
.rgba-primary-3 { color: rgba( 15,155,  0,1) }
.rgba-primary-4 { color: rgba( 20,209,  0,1) }

.rgba-secondary-1-0 { color: rgba( 57, 55,143,1) }	/* Main Secondary color (1) */
.rgba-secondary-1-1 { color: rgba(116,114,214,1) }
.rgba-secondary-1-2 { color: rgba( 73, 71,184,1) }
.rgba-secondary-1-3 { color: rgba( 16, 14,132,1) }
.rgba-secondary-1-4 { color: rgba( 23, 20,178,1) }

.rgba-secondary-2-0 { color: rgba(205,169, 57,1) }	/* Main Secondary color (2) */
.rgba-secondary-2-1 { color: rgba(255,221,116,1) }
.rgba-secondary-2-2 { color: rgba(255,210, 72,1) }
.rgba-secondary-2-3 { color: rgba(189,143,  0,1) }
.rgba-secondary-2-4 { color: rgba(255,192,  0,1) }

.rgba-complement-0 { color: rgba(201, 56, 63,1) }	/* Main Complement color */
.rgba-complement-1 { color: rgba(253,115,121,1) }
.rgba-complement-2 { color: rgba(251, 71, 80,1) }
.rgba-complement-3 { color: rgba(186,  0,  9,1) }
.rgba-complement-4 { color: rgba(251,  0, 13,1) }



/* Generated by Paletton.com © 2002-2014 */
/* http://paletton.com */
